### ISSUE TITLE
wed on PuTTY prints an 'x' for every newline when editing a linux files (LF ending)

### ISSUE THREAD

**Issue by nbenitez** [rgburke/wed#5]
Thank you very much for `wed` , I only considered the idea of working on my projects through `PuTTY` because of `wed` , no other terminal editor passes that mark for me.

Just reporting a small glitch in `PuTTY`, it shows an 'x' for every newline when editing files in my linux box.

Screenshot attached.

![wed_bug](https://user-images.githubusercontent.com/580854/30699128-56f272be-9efd-11e7-8640-a15ce4477a17.png)

**Comment by rgburke** [comment]
Thanks for trying wed and for reporting this. I was able to reproduce the issue using PuTTY.

The x's should be vertical lines. However PuTTY in UTF-8 mode ignores the VT100 "Alternate character set" which is used for line drawing. This is resolved for me by adding the following lines to the `~/.bashrc` on the remote machine being ssh'ed into:

```sh
export NCURSES_NO_UTF8_ACS=1
export LANG=en_GB.UTF-8
```
(You may want to use a differnet value for `LANG`)

With these environment variables set wed then displays correctly in PuTTY:

![image](https://user-images.githubusercontent.com/7596018/30721183-afa28154-9f22-11e7-9480-510b75c72664.png)

Could you try adding these variables to your `~/.bashrc`?
It may be that you only need `export NCURSES_NO_UTF8_ACS=1` for wed to work, but I needed both.

**Comment by nbenitez** [comment]
I confirm this fixes the problem for me (I also needed both two variables), I used `LANG=C.UTF-8` and btw the linux box is debian.

Thank you very much!
